### PR TITLE
Analysis parameters external readout

### PR DESCRIPTION
**Pull request by Kermaidy**
First pass to remove hard-coded thresholds and analysis parameters.
Other analysis parameters should be added to this new JSON file.
The first ID ("1") allows to increment configurations that can be later tested (e.g. study the analysis under different noise thresholds, ...)

### CODE REVIEW

**Comment by lzambell** [comment]
Can you add also noise filtering parameters (FFT and coherent groupings) ? Also, some reconstruction parameters will be electronic dependent (at least noise & pedestal), should it be added right now ?

**Comment by YoannKermaidic** [comment]
No problem, I'll add it too later.
(NB: In the train this afternoon...)

**Comment by YoannKermaidic** [comment]
For now, having a large hit search functions made numba-compatible does not speed-up the hit_finder step.
May want to split some while loops in smaller one.
-> To be moved to another PR (on Monday)

**Comment by YoannKermaidic** [comment]
Split analysis setting by configuration and electronics.
Add the possibility to set plots layout via config file instead of hard-coded values in `lardon.py`

**Comment by YoannKermaidic** [comment]
I think this PR can be approved and tentatively merged

**Review by lzambell — APPROVED** [review]

**Pull request merged**
