### PR TITLE
 Signal mask refinement with numba (supersedes #43)

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by YoannKermaidic** [comment]
It does not contain my signal masking dev in pedestal.py

**Comment by olantwin** [comment]
@YoannKermaidic you should be able to push more commits to the branch, if I missed any new changes you made.

**Comment by olantwin** [comment]
> 

Which commit was that in?

**Comment by olantwin** [comment]
Is this now what you had in mind, @YoannKermaidic ?

**Comment by olantwin** [comment]
Is this now what you had in mind, @YoannKermaidic ?

**Review by YoannKermaidic — APPROVED** [review]

**Pull request merged**
