### PR TITLE
Small typos fixed

### PR DESCRIPTION
**Pull request by lzambell**

### CODE REVIEW

**Review by Kermaidy — APPROVED** [review]

**Comment by YoannKermaidic** [comment]
With this PR, I cannot run Lardon:
` File "lardon.py", line 95, in <module>`
`    dc.reset_event()`
`  File "/eos/home-y/ykermaid/sw/dune-lardon/data_containers.py", line 36, in reset_event`
`    ped_rms[:,:] = 0.`
`NameError: name 'ped_rms' is not defined`

**Comment by olantwin** [comment]
Unless I'm mistaken, these commits don't touch that line.

**Comment by olantwin** [comment]
Wait, the `Files changed` tab shows very different changes than the individual commits...

**Comment by olantwin** [comment]
We can probably revert 4975b8f ?

**Comment by YoannKermaidic** [comment]
So one can probably merge my PR and then fix this problem since the fields were removed as they were apparently "useless".

**Pull request merged**
