### PR TITLE
Allow selecting a single event (as requested Fri)

### PR DESCRIPTION
**Pull request by olantwin**

### CODE REVIEW

**Comment by lzambell** [comment]
We should make a difference between requesting event x in that specific file and requesting to look at trigger x of the run. But the former can be trickier code-wise as you don't necessarily know in which subfile that trigger will be (and so far -sub argument is mandatory)

**Comment by olantwin** [comment]
Good point!

Is there a way for us to figure out the number of events per file without parsing it in it's entirety? Can we predict the size?

**Comment by lzambell** [comment]
Since we don't have the associated json file for each raw file, no ... As far as I saw, TDE have 110 events and BDE 161, but it might change ! I can only think of reading the first event of the file, get his trigger number and check if trigger_event_0 + nb_evt_in_file >= requested_trigger_nb, but that quite ugly !

**Comment by olantwin** [comment]
Split out one of the changes to #41

**Pull request closed without merging**
