### PR TITLE
Define config by start date - not period

### PR DESCRIPTION
**Pull request by YoannKermaidic**
I suggest we have a top field which corresponds to the starting date of the configuration. Then 
1. we know when the config is valid. The code can easily check which config to look into, given the data file it analyses.
2. we can easily append subsequent configurations

### CODE REVIEW

**Comment by olantwin** [comment]
Generally this is a great idea, but we should check that there's not a conditions database that will be used for the cold-box (so we're not reinventing the wheel/come up with an incompatible solution).

Maybe we could also separate things that will be constant for all data, but might change by data source/setup, from things that might vary over time? E.g. a `conditions.json` file for the latter and a `geo.json` or `config.json` for the former?

**Comment by lzambell** [comment]
Hi ! I also think it's a great general idea, but there will be a technical problem in this setup. For BDE data, the files have a timestamp in their name, so it'll be easy to find which config setup to use. But it's not the case for TDE files, ithe name is run_subnumber.something. The only way to know when the file was made is to read the event headers, and for that we need some informations from the config json file ...

**Comment by olantwin** [comment]
So that would also support splitting it into some general, constant info and time-dependent info in a separate file/database/whatever?

**Comment by YoannKermaidic** [comment]
Agree with you. We better split what is detector specific (`geo.json`) from DAQ/Slow control related items (and data/analysis - like paths). I would be specific in the naming, like `daq_config.json`.

One things we can do in this "LARDON" organisation is to create a repo called "lardon-metadata". We separate the software from metadata. And we maintain these metadata via Git - turned out to be simple and effective in my previous experiments.

For the geometry, we should already accomodate the file such that we have multiple setups possible: `coldbox_v1`, `np02_v1`, ...

For finding the TDE file timestamp, I think you do not need any config to parse the header (`reader.read_run_header()`), isn't it? So opening the time-dependent configs can happen right after I believe.

**Comment by YoannKermaidic** [comment]
I think the PR can be closed here and we refine our wishlist for the config files in https://github.com/dune-lardon/lardon/issues/4.

**Pull request closed without merging**
